[package]
name = "using_application_functionality_to_exploit_insecure_deserialization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
reqwest = { version = "0.11.20", features = ["blocking"] }
text-colorizer = "1.0.0"
lazy_static = "1.4.0"
regex = "1.10.0"
base64 = "0.21.5"
percent-encoding = "2.3.0"
